### ISSUE TITLE
unable to compile git since commit d76e6780

### ISSUE THREAD

**Issue by FelixSchwarz** [HBriese/fancon#12]
### Describe the bug
I'm unable to compile fancon since git commit d76e6780 (I used `cmake … -DNVIDIA_SUPPORT=OFF ..`).

    commit d76e6780ff87fdb4a76e65934b0592d6b338ef6d
    Author: Hayden Briese <haydenbriese@gmail.com>
    Date:   Thu May 7 02:02:38 2020 +1000

        - Fixed bug where configured NVIDIA devices may be run without NVIDIA control
        
        Signed-off-by: Hayden Briese <haydenbriese@gmail.com>

### Steps to Reproduce    

    $ make
    Scanning dependencies of target fancon
    [  5%] Building CXX object CMakeFiles/fancon.dir/src/main.cpp.o
    [ 11%] Building CXX object CMakeFiles/fancon.dir/src/Controller.cpp.o
    …/upstream.git/src/Controller.cpp:12:3: error: use of undeclared identifier 'NV'
      NV::init();
      ^
    1 error generated.
    make[2]: *** [CMakeFiles/fancon.dir/build.make:148: CMakeFiles/fancon.dir/src/Controller.cpp.o] Fehler 1
    make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/fancon.dir/all] Fehler 2
    make: *** [Makefile:150: all] Fehler 2

### Expected behavior      
compilation works

### Environment
 - Version: fancon git (commit d76e6780)
 - OS: Fedora 31
 - Kernel: 5.7.7
 - clang: 9.0.1
 - g++: 9.3.1

**Comment by hbriese** [comment]
Please pull the latest commit (563c9db9a4ac7c97a63203b2927cb3149b8632fc) and try again

**Comment by FelixSchwarz** [comment]
works for me now (I assume it was fixed in e0e6994e2b105f3fb617a192f4a6b8ddd3d1604a)
