### ISSUE TITLE
link error when build form source

### ISSUE THREAD

**Issue by hjw21century** [HBriese/fancon#16]
### Describe the bug
link error when build form source

### Steps to Reproduce    
cd fancon/build
cmake  ../
make -j

### Expected behavior      
link successfully

### Environment
 - Version: latest
 - OS: Ubuntu 20.04
 - Kernel: 5.4.0-65-generic

### Additional context
root@master-node:/home/ubuntu/WorkAtHome/fancon/build# make -j
Scanning dependencies of target fancon
[  4%] Building CXX object CMakeFiles/fancon.dir/src/main.cpp.o
[  9%] Building CXX object CMakeFiles/fancon.dir/src/proto/DevicesSpec.grpc.pb.cc.o
[ 14%] Building CXX object CMakeFiles/fancon.dir/src/proto/DevicesSpec.pb.cc.o
[ 19%] Building CXX object CMakeFiles/fancon.dir/src/Service.cpp.o
[ 23%] Building CXX object CMakeFiles/fancon.dir/src/Client.cpp.o
[ 28%] Building CXX object CMakeFiles/fancon.dir/src/SensorInterface.cpp.o
[ 33%] Building CXX object CMakeFiles/fancon.dir/src/FanInterface.cpp.o
[ 38%] Building CXX object CMakeFiles/fancon.dir/src/FanSysfs.cpp.o
[ 42%] Building CXX object CMakeFiles/fancon.dir/src/Devices.cpp.o
[ 47%] Building CXX object CMakeFiles/fancon.dir/src/NvidiaDevices.cpp.o
[ 52%] Building CXX object CMakeFiles/fancon.dir/src/Controller.cpp.o
[ 57%] Building CXX object CMakeFiles/fancon.dir/src/NvidiaNvml.cpp.o
[ 61%] Building CXX object CMakeFiles/fancon.dir/src/DellSMM.cpp.o
[ 66%] Building CXX object CMakeFiles/fancon.dir/src/NvidiaUtil.cpp.o
[ 71%] Building CXX object CMakeFiles/fancon.dir/src/FanDell.cpp.o
[ 76%] Building CXX object CMakeFiles/fancon.dir/src/SensorSysfs.cpp.o
[ 80%] Linking CXX executable fancon
CMakeFiles/fancon.dir/src/Service.cpp.o：在函数‘fc::Service::SubscribeDevices(grpc::ServerContext*, fc_pb::Empty const*, grpc::ServerWriter<fc_pb::Devices>*)’中：
/home/ubuntu/WorkAtHome/fancon/src/Service.cpp:78：对‘grpc::ServerContextBase::IsCancelled() const’未定义的引用
CMakeFiles/fancon.dir/src/Service.cpp.o：在函数‘operator()’中：
/home/ubuntu/WorkAtHome/fancon/src/Service.cpp:64：对‘grpc::ServerContextBase::IsCancelled() const’未定义的引用
CMakeFiles/fancon.dir/src/Service.cpp.o：在函数‘fc::Service::SubscribeFanStatus(grpc::ServerContext*, fc_pb::Empty const*, grpc::ServerWriter<fc_pb::FanStatus>*)’中：
/home/ubuntu/WorkAtHome/fancon/src/Service.cpp:150：对‘grpc::ServerContextBase::IsCancelled() const’未定义的引用
CMakeFiles/fancon.dir/src/Service.cpp.o：在函数‘operator()’中：
/home/ubuntu/WorkAtHome/fancon/src/Service.cpp:130：对‘grpc::ServerContextBase::IsCancelled() const’未定义的引用
/home/ubuntu/WorkAtHome/fancon/src/Service.cpp:137：对‘grpc::ServerContextBase::IsCancelled() const’未定义的引用
clang: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/fancon.dir/build.make:396: recipe for target 'fancon' failed
make[2]: *** [fancon] Error 1
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/fancon.dir/all' failed
make[1]: *** [CMakeFiles/fancon.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by hbriese** [comment]
I haven't been able to reproduce this issue on Ubuntu 21.04 using clang12. 
I assume you've installed all the dependencies.
Does the ppa version work for you?
