### ISSUE TITLE
build failure on Arch

### ISSUE THREAD

**Issue by notgood** [HBriese/fancon#17]
1) https://aur.archlinux.org/fancon.git fails to build on Arch, due to 404 link to https://github.com/hbriese/fancon/archive/v0.23.7.tar.gz
Actual tar.gz is published without starting "v"

2) Latest git https://aur.archlinux.org/fancon-git.git doesn't build as well, throws error:
```
CMake Error at CMakeLists.txt:65 (add_executable):
  Cannot find source file:

    /home/user/fancon-git/src/fancon/src/proto/DevicesSpec.pb.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .h .hh .h++
  .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc


CMake Error at CMakeLists.txt:65 (add_executable):
  No SOURCES given to target: fancon


CMake Generate step failed.  Build files cannot be regenerated correctly.
==> ERROR: A failure occurred in build().
    Aborting...
```
3) README config example is broken, due to commit https://github.com/hbriese/fancon/commit/e3779651fdfd621cbbb97fd2396f5aa8db9ae6b2#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by tutacat** [comment]
In fancon[AUR}, the source link needs to be replaced with either https://github.com/hbriese/${pkgname}/archive/refs/tags/${pkgver}.tar.gz in the PKGBUILD
