### ISSUE TITLE
Not doing it on a macBook Pro

### ISSUE THREAD

**Issue by Markospoko** [HBriese/fancon#2]
Hi,

It's not working on Mac, there's some msg fancon test gives that it can't find files in /sys/class/..., messy output about pwm or similar, what doesn't surprise when you're aware that all seems to be is in /sys/devices/platform/applesmc.768/ where you can change fans via rpm. Can this be fixed? Listing fans and sensors seems ok, it's applesmc/1:fan1, applesmc/1:fan2 for fans or alike..

T2MS
Mark

**Comment by rigred** [comment]
In short:
This was never made to work for OS X. 

So I presume you are running Linux on a Mac?

If so the sensor devices etc are all in different locations and esoterically laid out compared to the average laptop. It would be up to someone with a mac to investigate and provide info/code to make this work for macs.

**Comment by Markospoko** [comment]
I didn't say I ran it in OS X, where did you get this? :)

**Comment by hbriese** [comment]
As you say that the devices ARE detected, this will be fixed in the upcoming release.
However, if the layout differs significantly from https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface or it is otherwise still not working then I'd be happy to add support specifically

**Comment by hbriese** [comment]
Please try the latest release, and post the file created by 'fancon -i'
