### ISSUE TITLE
Please add how to use the program in the readme 

### ISSUE THREAD

**Issue by mrjohnc** [HBriese/fancon#3]
Hi 

Its would be really great if instructions on how to use the program were included in the readme. I understand that it is somehow controlled through the command line but other than that I can't work it out.

A GUI would be really amazing, currently there don't seem to be any other options for Ubuntu

Thaniks very much for making this

**Comment by Partagas150** [comment]
Yep... How to actually use the script would be wonderful!!!

A text File or a real Readme file is fine, but a GUI would be wonderful, not too sure wif we will see that!

**Comment by hbriese** [comment]
How is the new readme? Further information on what is unclear is appreciated
