### ISSUE TITLE
Uninstall (remove) instructions

### ISSUE THREAD

**Issue by deyspandan** [HBriese/fancon#7]
How can I cleanly remove fancon?

**Comment by hbriese** [comment]
If installed as a package (Debian / Ubuntu):
`sudo apt remove fancon`

If install through compilation:
make install generates an 'install_manifest.txt' which list all the files installed.
Thus any program installed with make can be uninstalled with
`sudo xargs rm < install_manifest.txt`

Config files can be removed with:
`sudo rm /etc/fancon.conf`
